/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    BookElement: typeof import('./src/components/book/book-list-element/BookListElement.vue')['default']
    BookElementHeader: typeof import('./src/components/book/book-list-element/BookElementHeader.vue')['default']
    BookElementUpvote: typeof import('./src/components/book/book-list-element/BookElementUpvote.vue')['default']
    BookListElement: typeof import('./src/components/book/book-list-element/BookListElement.vue')['default']
    BookListHeader: typeof import('./src/components/book/book-list-element/BookListHeader.vue')['default']
    BookPageSynopsis: typeof import('./src/components/BookPageSynopsis.vue')['default']
    BookPageTitle: typeof import('./src/components/BookPageTitle.vue')['default']
    BookSynopsis: typeof import('./src/components/book/BookSynopsis.vue')['default']
    BookTitle: typeof import('./src/components/book/BookTitle.vue')['default']
    BookUpvote: typeof import('./src/components/book/BookUpvote.vue')['default']
    Loader: typeof import('./src/components/Loader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
